# .yarnrc.yml
nodeLinker: node-modules # more compatible with ts-node-dev, jest, etc.
enableGlobalCache: true # faster installs across repos
enableImmutableInstalls: true # prevent accidental lockfile drift
nmMode: hardlinks-local # good perf on macOS
cacheFolder: .yarn/cache
