# Yarn 4 (Corepack) — repo root
# Node linker via node_modules for ts-node-dev/vitest compatibility
nodeLinker: node-modules

# Performance
enableGlobalCache: true # shared cache across repos
nmMode: hardlinks-local # fast on macOS
cacheFolder: .yarn/cache

# Install behavior
# IMPORTANT: allow lockfile updates while we change workspace globs and deps
enableImmutableInstalls: false

# Predictable hoisting across workspaces
nmHoistingLimits: workspaces

# Registry
npmRegistryServer: "https://registry.npmjs.org"
